### ISSUE TITLE
[Doc] Create downloadable MIDI files from the browser typo

### ISSUE THREAD

**Issue by GMartigny** [scribbletune/scribbletune.com#5]
In the documentation about MIDI file, on the part about `Create downloadable MIDI files from the browser`, the code example is wrong.
It's calling `midi` function twice:
```js
const bytes = midi(c, null); // Pass `null` as the second param to get bytes
const b64 = btoa(midi(c, bytes)); // Encode byte string from Scribbletune as base64
```

Current code base only return bytes infos via callback.
It should then be:
```js
const bytes = midi(c, null, (err, bytes) => { // Pass `null` as the second param to get bytes
	const b64 = btoa(bytes); // Encode byte string from Scribbletune as base64
});
```

**Comment by walmik** [comment]
Hi @GMartigny thank you so much for bringing this up! However I dont think we need to make it a callback as we are not doing any asynchronous activity. The issue was in this line `const b64 = btoa(midi(c, bytes));`
I had erroneously added `midi` in there... when all it needed was `const b64 = btoa(bytes);`

Here is a jsbin for this in case you wanna take a look, (Please note, it might instantly download the music.mid file if your default JS Bin settings have Auto Run JS selected)
https://jsbin.com/nabirinovo/edit?html,js,console,output

I have updated the documentation. You can close this issue if it has addressed the issue you brought up. Thank you for your time, Sincerely.

**Comment by GMartigny** [comment]
From what I see on the source, the `midi` function now return `undefined` when using `null` as filename.
https://github.com/scribbletune/scribbletune/blob/f914eee74f272ad13fa4b751b14f7c4b5646069f/src/midi.js#L38

**Comment by walmik** [comment]
Hi @GMartigny Sorry for the delay in the response here, I was a bit held up with work. You were right (and thank you for your persistence). I ve now changed the JSBin to reflect the callback nature: https://jsbin.com/tusogupiji/edit?html,js,console,output

I ve also updated this in the docs: https://scribbletune.com/documentation/core/midi

**Comment by GMartigny** [comment]
Since the output process is synchronous, you don't need a callback. Returning the bytes directly could be the next improvement path for the function.
Thanks to you for the awesome work.
